'use strict';
const assert = require('assert');
const ops = require('../server/internal-ops');
assert.equal(ops.scopeDiff({ service: '자막', units: 5 }, { service: '자막', units: 5 }).classification, 'IN_SCOPE');
assert.equal(ops.scopeDiff({ units: 5 }, { units: 6 }).requiresConsent, true);
assert.equal(ops.scopeDiff({}, { units: '' }).requiresConsent, true);
assert.equal(ops.profitReconciliation([{ orderId: 'a', settledKrw: 44000, feesKrw: 1000 }]).totals.contribution, 43000);
assert.equal(ops.profitReconciliation([{ settlementEventId: 'e', orderId: 'a', settledKrw: 44000 }, { settlementEventId: 'e', orderId: 'a', settledKrw: 44000 }]).rows.length, 1);
assert.throws(() => ops.profitReconciliation([{ orderId: 'usd', currency: 'USD', settledKrw: 10 }]), /mixed_currency/);
assert.equal(ops.profitReconciliation([{ orderId: 'pending', paidKrw: 44000 }]).rows[0].verified, false);
assert.equal(ops.capacityEstimate({ minutesPerUnit: 10, units: 2, availableMinutes: 30 }).decision, 'ACCEPT');
assert.equal(ops.capacityEstimate({ minutesPerUnit: 20, units: 2, availableMinutes: 30 }).decision, 'REJECT_CAPACITY');
const simulation = ops.simulation('timeout_unknown');
assert.equal(simulation.externalCalls, 0);
assert.equal(ops.validateInvariant(simulation).pass, true);
assert.equal(ops.validateInvariant(ops.simulation('duplicate_delivery')).pass, true);
assert.equal(ops.exceptionList([{ id: 'x', status: 'VERIFIED_SUCCESS' }, { id: 'y', status: 'UNKNOWN' }]).length, 1);
assert.equal(ops.funnel([{ eventId: 'e1', stage: 'received' }, { eventId: 'e1', stage: 'received' }]).counts.received, 1);
assert.equal(ops.funnel([]).denominatorZero, true);
const responseSimulation = ops.customerResponseSimulation({ count: 20, responseRate: 0.01, seed: 'fixed-no-response' });
assert.equal(responseSimulation.noResponse + responseSimulation.responded, 20);
assert.equal(responseSimulation.responseRate, 0.01);
const responseBranch = ops.customerResponseSimulation({ count: 1, responseRate: 1, seed: 'response-branch' });
assert.equal(responseBranch.responded, 1);
assert.equal(ops.intakeFit({ supported: true, withinBudget: true, withinCapacity: true, requiredInfoComplete: true }).fit, 'QUALIFIED');
assert.equal(ops.intakeFit({ requiredInfoComplete: false }).fit, 'NEEDS_INFO');
assert.equal(ops.noResponseGuard({ status: 'HOLD_NO_RESPONSE', pollCount: 10 }).externalCallsAllowed, false);
assert.equal(ops.expectedContribution({ responseRate: 0.01, completionRate: 0.2, contributionKrw: 50000 }).expectedKrw, 100);
console.log('internal-ops tests passed');
